### ISSUE TITLE
Not a git repository Error

### ISSUE THREAD

**Issue by kotturi-mahipal** [naiborhujosua/Machine-Learning-Specialization#2]
[
![image](https://github.com/naiborhujosua/Machine-Learning-Specialization/assets/109608873/dbe41402-2dec-43bb-971e-39222af489f0)
](url)

**Comment by naiborhujosua** [comment]
you can try out one of the possible answers on [Stackoverflow](https://stackoverflow.com/questions/22041752/github-clone-succeeded-but-checkout-failed). One that worked for me is `git config --system core.longpaths true`.
